// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID            int64
	ShortCode     string
	LongUrl       string
	LongUrlHash   string
	UserID        pgtype.Int8
	IsCustomAlias bool
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	IsActive      bool
}

type User struct {
	ID         int64
	Email      string
	ApiKeyHash string
	CreatedAt  pgtype.Timestamptz
}
