// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: url.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    id,
    short_code,
    long_url,
    long_url_hash,
    user_id,
    is_custom_alias,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, short_code, long_url, long_url_hash, user_id, is_custom_alias, created_at, expires_at, is_active
`

type CreateURLParams struct {
	ID            int64
	ShortCode     string
	LongUrl       string
	LongUrlHash   string
	UserID        pgtype.Int8
	IsCustomAlias bool
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL,
		arg.ID,
		arg.ShortCode,
		arg.LongUrl,
		arg.LongUrlHash,
		arg.UserID,
		arg.IsCustomAlias,
		arg.ExpiresAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.LongUrlHash,
		&i.UserID,
		&i.IsCustomAlias,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, long_url, long_url_hash, user_id, is_custom_alias, created_at, expires_at, is_active
FROM urls
WHERE short_code = $1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.LongUrlHash,
		&i.UserID,
		&i.IsCustomAlias,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const getURLByUserAndHash = `-- name: GetURLByUserAndHash :one
SELECT id, short_code, long_url, long_url_hash, user_id, is_custom_alias, created_at, expires_at, is_active
FROM urls
WHERE user_id = $1
AND long_url_hash = $2
`

type GetURLByUserAndHashParams struct {
	UserID      pgtype.Int8
	LongUrlHash string
}

func (q *Queries) GetURLByUserAndHash(ctx context.Context, arg GetURLByUserAndHashParams) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByUserAndHash, arg.UserID, arg.LongUrlHash)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.LongUrlHash,
		&i.UserID,
		&i.IsCustomAlias,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}
