// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, api_key_hash)
VALUES ($1, $2, $3)
RETURNING id, email, api_key_hash, created_at
`

type CreateUserParams struct {
	ID         int64
	Email      string
	ApiKeyHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.ApiKeyHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAPIKeyHash = `-- name: GetUserByAPIKeyHash :one
SELECT id, email, api_key_hash, created_at FROM users WHERE api_key_hash = $1
`

func (q *Queries) GetUserByAPIKeyHash(ctx context.Context, apiKeyHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKeyHash, apiKeyHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}
